### ISSUE TITLE
Sample app not working in N OS

### ISSUE THREAD

**Issue by hammmmy** [andengineering/BLE_Sample_Android#11]
We tested the sample app on N OS on Samsung Galaxy devices. 
We cannot get data from the device on N OS even with latest firmware "e". In the sample app we get error 14 from GATT.
In our own implmentation, we are always getting INSUFFICIENT_AUTHENTICATION error. However, in A&D connect app in market, we don't get such error and data is received successfully. Could you tell us how to resolve this issue? Thanks.

**Comment by sim0512** [comment]
Are you able to pair with the 651 monitor successfully? Insufficient authentication happens when the pairing fails. Can you send me the code snippet of your app and the apk. I would like to run it here and test it

**Comment by hammmmy** [comment]
Hi, we got in touch with the A&D team on a seperate loop and fixed the issue by adding delay before calling discoverServices() as a workaround. Thanks!
